<?php

namespace App\Component\Base\Filesystem;


class Aux
{
    /**
     *
    */
    public static function append($filename, $content) : void
    {
        $fd = fopen($filename, 'a+');
        fwrite($fd, $content, strlen($content));
        fclose($fd);
    }

    /**
     *
     */
    public static function phpAutogenerated($filename) : void
    {
        $timestamp = date('Y-m-d h:i:s');
        $content = <<<DOC
<?php
//
//  Auto-generated on $timestamp, DO NOT modify this file     
//

DOC;
        $fd = fopen($filename, 'w');
        fwrite($fd, $content, strlen($content));
        fclose($fd);
    }
}